-- MySQL Script generated by MySQL Workbench
-- Sat May 28 16:34:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE pruebas2;
USE pruebas2;

-- -----------------------------------------------------
-- Table departamentos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamentos` (
  `codDepto` VARCHAR(4) NOT NULL,
  `nombeDepto` VARCHAR(20) NOT NULL,
  `ciudad` VARCHAR(15) NULL,
  `codDirector` VARCHAR(12) NULL,
  PRIMARY KEY (`codDepto`));


-- -----------------------------------------------------
-- Table empleados
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleados` (
  `nDIEmp` VARCHAR(12) NOT NULL,
  `nomEmp` VARCHAR(30) NOT NULL,
  `sexEmp` CHAR(1) NOT NULL,
  `fecNac` DATE NOT NULL,
  `salEmp` FLOAT NOT NULL,
  `comisionEmp` FLOAT NOT NULL,
  `cargoEmp` VARCHAR(15) NOT NULL,
  `jefeID` VARCHAR(12) NULL,
  `codDepto` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`nDIEmp`),
  INDEX `codDepto_idx` (`codDepto` ASC) VISIBLE,
  INDEX `jefeID_idx` (`jefeID` ASC) VISIBLE,
  CONSTRAINT `codDepto`
    FOREIGN KEY (`codDepto`)
    REFERENCES `mydb`.`departamentos` (`codDepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `jefeID`
    FOREIGN KEY (`jefeID`)
    REFERENCES `mydb`.`empleados` (`jefeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
